services:
  # The Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: engineer-test-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this in a real project
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # Persist database data using a named volume
      - db_data:/var/lib/mysql

  # The Web Server Service (PHP + Apache)
  web:
    # Build the image from the Dockerfile in the 'backend' directory
    build:
      context: ./backend
    container_name: engineer-test-web
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: employee_db
      DB_USER: user
      DB_PASS: password

# Define the named volume for data persistence
volumes:
  db_data: